"""Create LOIForm table

Revision ID: 11f9647367b6
Revises: 
Create Date: 2025-10-24 19:27:47.795770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f9647367b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loi_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('purchase_price', sa.String(length=50), nullable=True),
    sa.Column('revenue', sa.String(length=50), nullable=True),
    sa.Column('avg_sde', sa.String(length=50), nullable=True),
    sa.Column('seller_role', sa.String(length=120), nullable=True),
    sa.Column('reason_for_selling', sa.Text(), nullable=True),
    sa.Column('owner_involvement', sa.Text(), nullable=True),
    sa.Column('customer_concentration_risk', sa.Text(), nullable=True),
    sa.Column('deal_competitiveness', sa.Text(), nullable=True),
    sa.Column('seller_note_open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loi_form')
    # ### end Alembic commands ###
