"""Add new LOI form fields

Revision ID: 38376aa09025
Revises: 11f9647367b6
Create Date: 2025-10-27 23:26:31.427056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38376aa09025'
down_revision = '11f9647367b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loi_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cim_fit_narrative', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('relate_to_narrative', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('likes_dislikes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('questions_concerns', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirm_terms', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loi_form', schema=None) as batch_op:
        batch_op.drop_column('confirm_terms')
        batch_op.drop_column('uploaded_file')
        batch_op.drop_column('questions_concerns')
        batch_op.drop_column('likes_dislikes')
        batch_op.drop_column('relate_to_narrative')
        batch_op.drop_column('cim_fit_narrative')

    # ### end Alembic commands ###
