"""Add CIMForm table

Revision ID: afcfe7609c86
Revises: 38376aa09025
Create Date: 2025-10-28 02:55:19.721800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcfe7609c86'
down_revision = '38376aa09025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cim_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('avg_sde', sa.Float(), nullable=True),
    sa.Column('seller_role', sa.String(length=100), nullable=True),
    sa.Column('reason_for_selling', sa.Text(), nullable=False),
    sa.Column('owner_involvement', sa.Text(), nullable=True),
    sa.Column('gm_in_place', sa.String(length=10), nullable=True),
    sa.Column('tenure_gm', sa.String(length=50), nullable=True),
    sa.Column('num_employees', sa.Integer(), nullable=True),
    sa.Column('total_adjustments', sa.Float(), nullable=True),
    sa.Column('search_fit', sa.String(length=10), nullable=False),
    sa.Column('search_connection', sa.Text(), nullable=True),
    sa.Column('deal_interest', sa.Text(), nullable=True),
    sa.Column('questions_concerns', sa.Text(), nullable=True),
    sa.Column('uploaded_file', sa.String(length=300), nullable=True),
    sa.Column('confirm_terms', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loi_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('avg_sde', sa.Float(), nullable=True),
    sa.Column('seller_role', sa.String(length=100), nullable=True),
    sa.Column('reason_for_selling', sa.Text(), nullable=True),
    sa.Column('owner_involvement', sa.Text(), nullable=True),
    sa.Column('customer_concentration_risk', sa.Text(), nullable=True),
    sa.Column('deal_competitiveness', sa.Text(), nullable=True),
    sa.Column('seller_note_open', sa.Boolean(), nullable=True),
    sa.Column('cim_fit_narrative', sa.String(length=10), nullable=True),
    sa.Column('relate_to_narrative', sa.Text(), nullable=True),
    sa.Column('likes_dislikes', sa.Text(), nullable=True),
    sa.Column('questions_concerns', sa.Text(), nullable=True),
    sa.Column('uploaded_file', sa.String(length=300), nullable=True),
    sa.Column('confirm_terms', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loi_form')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loi_form',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('purchase_price', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('revenue', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('avg_sde', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('seller_role', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('reason_for_selling', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_involvement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_concentration_risk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deal_competitiveness', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seller_note_open', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cim_fit_narrative', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('relate_to_narrative', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('likes_dislikes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('questions_concerns', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('confirm_terms', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('loi_form_pkey'))
    )
    op.drop_table('loi_forms')
    op.drop_table('cim_forms')
    # ### end Alembic commands ###
